--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.5

-- Started on 2025-11-04 11:26:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 66823)
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    role character varying(16) NOT NULL,
    content text NOT NULL,
    ts timestamp without time zone DEFAULT now() NOT NULL,
    conversation_id character varying(255) NOT NULL,
    parent_message_id bigint,
    title character varying(120)
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 66822)
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 66805)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 66810)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 3418 (class 2613 OID 58409)
-- Name: 58409..58410; Type: BLOB METADATA; Schema: -; Owner: postgres
--

SELECT pg_catalog.lo_create('58409');
SELECT pg_catalog.lo_create('58410');

ALTER LARGE OBJECT 58409 OWNER TO postgres;
ALTER LARGE OBJECT 58410 OWNER TO postgres;

--
-- TOC entry 3417 (class 0 OID 66823)
-- Dependencies: 220
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_message (id, role, content, ts, conversation_id, parent_message_id, title) FROM stdin;
1	USER	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng	2025-10-28 09:42:43.453194	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	\N	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng
2	ASSISTANT	{"message":"Xin lỗi, tôi không tìm thấy chuyến bay nào cho yêu cầu của bạn. Bạn có muốn tìm kiếm vào ngày khác không?","next_request_suggestions":["Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng vào ngày khác","Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng với các tiêu chí khác"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 09:42:47.389823	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	1	\N
3	USER	bạn có tìm trong ngày hôm nay không ?	2025-10-28 09:44:01.754755	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	2	\N
4	ASSISTANT	{"message":"Tôi tìm thấy một chuyến bay từ Hồ Chí Minh đến Đà Nẵng vào ngày 28 tháng 10 năm 2025. Chuyến bay này khởi hành lúc 13:15 và đến lúc 14:50, với giá 1.274.753 VND. Bạn có muốn đặt chuyến bay này không?","next_request_suggestions":["Có","Không"],"results":[{"type":"flight","title":"Vietnam Airlines VN230","subtitle":"SGN → DAD • 13:15-14:50","description":null,"imageUrl":null,"ids":{"flightId":"5","fareId":"1ce43f2f-767b-4eec-b74e-efdc4e01efff","scheduleId":"d45c7159-8c38-4e60-8051-75b3c9247e21"},"metadata":{"price":"1274753","duration":"1h 35m","airline":"Vietnam Airlines","departure_time":"13:15","arrival_time":"14:50","available_seats":175,"aircraft":"A380","currency":"VND"}}],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 09:44:06.617917	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	1	\N
5	USER	Không	2025-10-28 09:46:34.991913	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	4	\N
6	ASSISTANT	{"message":"Được rồi, tôi sẽ tìm các chuyến bay khác cho bạn. Bạn muốn tìm chuyến bay đi đâu và vào thời gian nào?","next_request_suggestions":["Tìm chuyến bay từ Hà Nội đến Huế","Tìm chuyến bay từ TP.HCM đến Hà Nội vào ngày mai","Tìm chuyến bay từ Đà Nẵng đến Đà Lạt vào cuối tuần này"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 09:46:36.813382	phamduyhuy:026ce551-c4c2-4977-9c1c-ff324172fae8	1	\N
7	USER	Tìm địa điểm ăn uống ngon tại Hội An	2025-10-28 10:15:34.676313	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	\N	Tìm địa điểm ăn uống ngon tại Hội An
8	ASSISTANT	{"message":"Đã xử lý yêu cầu nhưng không có kết quả.","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 10:15:38.560351	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	7	\N
9	USER	Tìm địa điểm ăn uống ngon tại Hội An	2025-10-28 10:16:20.932037	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	8	\N
10	ASSISTANT	{"message":"Tôi tìm thấy một số nhà hàng ở Hội An. Bạn có muốn xem danh sách không?","next_request_suggestions":["Có","Không","Cho tôi biết thêm về Nhà hàng Bạch Mã"],"results":[{"type":"info","title":"Nhà hàng Bạch Mã","subtitle":"Phú Lộc, 49800, Vietnam","description":"Phú Lộc, 49800, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.19410828,107.85314639],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Am Thuc Co Tu","subtitle":"Nam Đông, 49700, Vietnam","description":"Unnamed, Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.14663096,107.72839314],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Nhà Hàng Thảo Nguyên Xanh","subtitle":"Nam Đông, 49700, Vietnam","description":"53 Tả Trạch, Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.16322762,107.72568367],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"MĂNG Garden Coffee & Restaurant","subtitle":"Nam Đông, 49700, Vietnam","description":"Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.1584587,107.72524237],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Quán Bin Mập","subtitle":"Phú Lộc, 49800, Vietnam","description":"Phú Lộc, 49800, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.26202761,107.87843827],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Nhà hàng An Phú","subtitle":"Nam Đông, 49700, Vietnam","description":"Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.18671015,107.72624394],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Quán Điểm Hẹn","subtitle":"Nam Đông, 49700, Vietnam","description":"Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.1862558,107.72576026],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"3A Quan","subtitle":"Nam Đông, 49700, Vietnam","description":"70 Tả Trạch, Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.16810142,107.72380142],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"3A quán","subtitle":"Nam Đông, 49700, Vietnam","description":"70 Tả Trạch, Nam Đông, 49700, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.16812982,107.72379306],"type":"poi","category":"food, food and drink, restaurant"}},{"type":"info","title":"Quán mụ Hạnh","subtitle":"Phú Lộc, 49800, Vietnam","description":"Phú Lộc, 49800, Vietnam","imageUrl":null,"ids":{"poi_id":"8030171000000000000"},"metadata":{"coordinates":[16.26141537,107.8812564],"type":"poi","category":"breakfast restaurant, food, food and drink, restaurant"}}],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 10:16:28.788421	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	7	\N
11	USER	Có	2025-10-28 10:17:46.75918	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	10	\N
12	ASSISTANT	{"message":"Tôi xin lỗi, tôi không thể tìm thấy bất kỳ nhà hàng nào ở Hội An. Bạn có muốn tôi tìm kiếm ở một thành phố khác không?","next_request_suggestions":["Có","Không"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 10:17:48.491733	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	7	\N
13	USER	Không	2025-10-28 10:17:55.337243	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	12	\N
14	ASSISTANT	{"message":"Tôi xin lỗi, tôi không thể tìm thấy bất kỳ nhà hàng nào ở Hội An. Bạn có muốn tôi tìm kiếm ở một thành phố khác không?","next_request_suggestions":["Có","Không"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 10:17:56.558819	phamduyhuy:9bbf31ea-1636-42a5-b92b-3f9078b00812	7	\N
15	USER	Gợi ý khách sạn 4 sao tại Đà Nẵng	2025-10-28 12:18:05.376192	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	\N	Gợi ý khách sạn 4 sao tại Đà Nẵng
16	ASSISTANT	{"message":"Đây là một số khách sạn 4 sao ở Đà Nẵng:","next_request_suggestions":["Tìm khách sạn 5 sao ở Đà Nẵng","Tìm khách sạn giá rẻ ở Đà Nẵng","Tìm chuyến bay đến Đà Nẵng"],"results":[{"type":"hotel","title":"TMS Hotel Da Nang Beach","subtitle":"Đà Nẵng, Vietnam • 4★","description":null,"imageUrl":"https://media.gettyimages.com/id/504341190/photo/china-beach-da-nang-vietnam.jpg?s=612x612&w=0&k=20&c=VD1zK5NbnSy4sgFo83d-kLRTQQN8iNgV8lngGFFZ9ME=","ids":{"hotelId":"20"},"metadata":{"amenities":["Free WiFi","Swimming Pool","Fitness Center","Spa & Wellness","Restaurant","Bar & Lounge","Business Center","Conference Room","Airport Shuttle","Parking","Room Service","Laundry Service","Air Conditioning","Mini Bar","Safe Deposit Box","Balcony/Terrace","Sea View","City View","Pet Friendly","Kids Club","Hồ bơi ngoài trời","Spa & Massage","Phòng gym","Nhà hàng","Bar/Lounge","Dịch vụ đưa đón sân bay","Bãi biển riêng","Sân golf","Dịch vụ giặt ủi","Trông trẻ"],"location":"356 Nguyễn Văn Thoại, Ngũ Hành Sơn, Đà Nẵng, Vietnam","price":"5000000.0 VND","rating":4}}],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:18:16.990719	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
17	USER	Tìm chuyến bay từ HCM đến Đà Nẵng	2025-10-28 12:19:27.074646	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
18	ASSISTANT	{"message":"Tôi không tìm thấy chuyến bay nào từ TP.HCM đến Đà Nẵng. Vui lòng kiểm tra lại thông tin hoặc thử tìm kiếm với các tiêu chí khác.","next_request_suggestions":["Tìm khách sạn ở Đà Nẵng","Tìm chuyến bay đến Hà Nội","Thời tiết ở Đà Nẵng"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:19:32.455835	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
19	USER	hmm hãy thử lại xem, nhưng mà là trong ngày 30 tháng 10	2025-10-28 12:22:19.978914	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
20	ASSISTANT	{"message":"Xin lỗi, tôi gặp lỗi khi xử lý yêu cầu của bạn. Vui lòng thử lại.","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:22:28.666051	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
21	USER	hãy thử lại	2025-10-28 12:24:55.296168	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
22	ASSISTANT	{"message":"Xin lỗi, tôi gặp lỗi khi xử lý yêu cầu của bạn. Vui lòng thử lại.","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:25:01.688009	phamduyhuy:bc71c13e-20dc-4316-be30-4369cad3be6e	15	\N
23	USER	Tìm khách sạn ở Huế	2025-10-28 12:27:59.77743	phamduyhuy:f8a7b7e9-0cc6-4830-9b54-d72dffb24be0	\N	Tìm khách sạn ở Huế
24	ASSISTANT	{"message":"Dưới đây là một số khách sạn ở Huế cho ngày 28-10-2025 đến 29-10-2025:","next_request_suggestions":["Tìm khách sạn 5 sao ở Huế","Tìm khách sạn có hồ bơi ở Huế","Tìm khách sạn giá rẻ ở Huế"],"results":[{"type":"hotel","title":"La Residence Hue Hotel & Spa","subtitle":"Huế, Vietnam • 5★","description":null,"imageUrl":"https://tomanetwanderers.com/wp-content/uploads/2020/03/Vietnam_Hue_Temple.webp","ids":{"hotelId":"16"},"metadata":{"amenities":["Free WiFi","Swimming Pool","Fitness Center","Spa & Wellness","Restaurant","Bar & Lounge","Business Center","Conference Room","Airport Shuttle","Parking","Room Service","Laundry Service","Air Conditioning","Mini Bar","Safe Deposit Box","Balcony/Terrace","Sea View","City View","Pet Friendly","Kids Club","Hồ bơi ngoài trời","Spa & Massage","Phòng gym","Nhà hàng","Bar/Lounge","Dịch vụ đưa đón sân bay","Bãi biển riêng","Sân golf","Dịch vụ giặt ủi","Trông trẻ"],"location":"5 Lê Lợi, Thành phố Huế, Thừa Thiên Huế, Vietnam","price":"5000000.0 VND","rating":5}},{"type":"hotel","title":"Cherish Hue Hotel","subtitle":"Huế, Vietnam • 4★","description":null,"imageUrl":"https://www.backpackerswanderlust.com/wp-content/uploads/2021/10/imperial-city-of-hue-25.jpg","ids":{"hotelId":"26"},"metadata":{"amenities":["Free WiFi","Swimming Pool","Fitness Center","Spa & Wellness","Restaurant","Bar & Lounge","Business Center","Conference Room","Airport Shuttle","Parking","Room Service","Laundry Service","Air Conditioning","Mini Bar","Safe Deposit Box","Balcony/Terrace","Sea View","City View","Pet Friendly","Kids Club","Hồ bơi ngoài trời","Spa & Massage","Phòng gym","Nhà hàng","Bar/Lounge","Dịch vụ đưa đón sân bay","Bãi biển riêng","Sân golf","Dịch vụ giặt ủi","Trông trẻ"],"location":"25A Phan Bội Châu, Thành phố Huế, Thừa Thiên Huế, Vietnam","price":"5000000.0 VND","rating":4}},{"type":"hotel","title":"Moonlight Hotel Hue","subtitle":"Huế, Vietnam • 3★","description":null,"imageUrl":"https://vmcar.com.vn/wp-content/uploads/2024/05/hue-city-vietnam-thien-mu-pagoda.webp","ids":{"hotelId":"30"},"metadata":{"amenities":["Free WiFi","Swimming Pool","Fitness Center","Spa & Wellness","Restaurant","Bar & Lounge","Business Center","Conference Room","Airport Shuttle","Parking","Room Service","Laundry Service","Air Conditioning","Mini Bar","Safe Deposit Box","Balcony/Terrace","Sea View","City View","Pet Friendly","Kids Club","Hồ bơi ngoài trời","Spa & Massage","Phòng gym","Nhà hàng","Bar/Lounge","Dịch vụ đưa đón sân bay","Bãi biển riêng","Sân golf","Dịch vụ giặt ủi","Trông trẻ"],"location":"20 Phạm Ngũ Lão, Thành phố Huế, Thừa Thiên Huế, Vietnam","price":"5000000.0 VND","rating":3}},{"type":"hotel","title":"Banyan Tree Lang Co","subtitle":"Huế, Vietnam • 5★","description":null,"imageUrl":"https://upload.wikimedia.org/wikipedia/commons/4/48/Vietnam,_Hue,_Imperial_City_of_Hue,_The_Meridian_Gate.jpg","ids":{"hotelId":"6"},"metadata":{"amenities":["Free WiFi","Swimming Pool","Fitness Center","Spa & Wellness","Restaurant","Bar & Lounge","Business Center","Conference Room","Airport Shuttle","Parking","Room Service","Laundry Service","Air Conditioning","Mini Bar","Safe Deposit Box","Balcony/Terrace","Sea View","City View","Pet Friendly","Kids Club","Hồ bơi ngoài trời","Spa & Massage","Phòng gym","Nhà hàng","Bar/Lounge","Dịch vụ đưa đón sân bay","Bãi biển riêng","Sân golf","Dịch vụ giặt ủi","Trông trẻ"],"available_rooms":[{"available":true,"capacity":6,"pricePerNight":2800000.0,"roomId":"6","roomType":"Family Room"},{"available":true,"capacity":2,"pricePerNight":1600000.0,"roomId":"16","roomType":"Pool View Room"}],"location":"Chan May – Lang Co Commune, Canh Duong Village, Phú Lộc, Thành phố Huế, Vietnam","price":"1600000.0 VND","rating":5}}],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:28:19.213623	phamduyhuy:f8a7b7e9-0cc6-4830-9b54-d72dffb24be0	23	\N
25	USER	tìm chuyến bay từ HCM đến Huế vào ngày 28	2025-10-28 12:29:33.869478	phamduyhuy:f8a7b7e9-0cc6-4830-9b54-d72dffb24be0	23	\N
26	ASSISTANT	{"message":"Dưới đây là các chuyến bay từ TP.HCM đến Huế vào ngày 28-10-2025:","next_request_suggestions":["Tìm chuyến bay thẳng từ TP.HCM đến Huế","Tìm chuyến bay giá rẻ từ TP.HCM đến Huế","Tìm chuyến bay của Vietnam Airlines từ TP.HCM đến Huế"],"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:29:38.040993	phamduyhuy:f8a7b7e9-0cc6-4830-9b54-d72dffb24be0	23	\N
27	USER	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng	2025-10-28 12:50:54.69855	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	\N	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng
28	ASSISTANT	{"message":"Xin lỗi, tôi gặp lỗi khi xử lý yêu cầu của bạn. Vui lòng thử lại.","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:51:13.604133	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	27	\N
29	USER	thử lại xem	2025-10-28 12:52:43.952938	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	27	\N
30	ASSISTANT	{"message":"Tôi có thể tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng. Bạn muốn bay vào ngày nào?","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:52:50.495822	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	27	\N
31	USER	ngày 30 thang 10	2025-10-28 12:54:07.562925	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	27	\N
32	ASSISTANT	{"message":"Xin lỗi, tôi không tìm thấy chuyến bay nào cho ngày 30 tháng 10. Vui lòng chọn ngày khác hoặc thử lại sau.","next_request_suggestions":null,"results":[],"requiresConfirmation":false,"confirmationContext":null}	2025-10-28 12:54:15.641702	phamduyhuy:8d17cf68-1459-4d0b-b2a9-1776905f73a9	27	\N
33	USER	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng	2025-10-29 00:58:28.729234	phamduyhuy:d7baca56-992f-4b26-bc11-4f2b89bed53a	\N	Tìm chuyến bay từ Hồ Chí Minh đến Đà Nẵng
34	ASSISTANT	{"message":"Tôi tìm thấy các chuyến bay sau từ Hồ Chí Minh đến Đà Nẵng vào ngày 2025-10-29:","next_request_suggestions":["Tìm chuyến bay khứ hồi","Tìm khách sạn tại Đà Nẵng","Thời tiết Đà Nẵng"],"results":[{"type":"flight","title":"Vietnam Airlines VN230","subtitle":"SGN → DAD • 06:35-08:10","description":null,"imageUrl":null,"ids":{"fareId":"ff4637f1-06e7-4648-aa5e-0b81a4a48adb","flightId":"5","scheduleId":"198e4f48-78d9-47c5-b02f-f8a375722b5e"},"metadata":{"aircraft":"A380","airline":"Vietnam Airlines","arrival_time":"08:10","available_seats":195,"departure_time":"06:35","duration":"1h 35m","price":"1,421,927"}}],"requiresConfirmation":false,"confirmationContext":null}	2025-10-29 00:58:36.57677	phamduyhuy:d7baca56-992f-4b26-bc11-4f2b89bed53a	33	\N
\.


--
-- TOC entry 3414 (class 0 OID 66805)
-- Dependencies: 217
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
001-create-chat-tables	codex	db/changelog/001-create-chat-tables.yaml	2025-10-07 17:56:31.24354	1	EXECUTED	9:2df33b24da78aba53fdc23c8929b23b6	createTable tableName=chat_conversation; createIndex indexName=ix_chat_conversation_user_id, tableName=chat_conversation; createTable tableName=chat_message; addForeignKeyConstraint baseTableName=chat_message, constraintName=fk_chat_message_conver...		\N	4.31.1	\N	\N	9859787830
1760458517215-4	PhamDuyHuy	db/changelog/14-01-changelog.sql	2025-10-14 16:17:49.095925	2	EXECUTED	9:4b124530b85526774e4fc9c5fc64e5c6	sql		\N	4.31.1	\N	\N	0458667939
1760458517215-3	PhamDuyHuy	db/changelog/14-01-changelog.sql	2025-10-14 16:17:49.119353	3	EXECUTED	9:619fe469e17879aba308108c9d7d68da	sql		\N	4.31.1	\N	\N	0458667939
1760458517215-5	PhamDuyHuy	db/changelog/14-01-changelog.sql	2025-10-14 16:17:49.136898	4	EXECUTED	9:01dcacc37bbbdcc7985ac948b28b22d3	sql		\N	4.31.1	\N	\N	0458667939
1760458517215-1	PhamDuyHuy	db/changelog/14-01-changelog.sql	2025-10-14 16:17:49.150027	5	EXECUTED	9:889a1dc012c7384b25747a46d5b99177	sql		\N	4.31.1	\N	\N	0458667939
1760458517215-2	PhamDuyHuy	db/changelog/14-01-changelog.sql	2025-10-14 16:17:49.16232	6	EXECUTED	9:525eeaaa4ff9fda1866c5934cc697805	sql		\N	4.31.1	\N	\N	0458667939
1760536349141-1	PhamDuyHuy	db/changelog/15-01-changelog.sql	2025-10-15 14:19:54.693785	7	EXECUTED	9:fd7b59d9168bb17caf656f557b2cfca6	sql		\N	4.31.1	\N	\N	0537993386
1760536349141-3	PhamDuyHuy	db/changelog/15-01-changelog.sql	2025-10-15 14:19:54.723783	8	EXECUTED	9:619fe469e17879aba308108c9d7d68da	sql		\N	4.31.1	\N	\N	0537993386
1760536349141-4	PhamDuyHuy	db/changelog/15-01-changelog.sql	2025-10-15 14:19:54.741505	9	EXECUTED	9:063372a9dab68b3fa86513049ce17e02	sql		\N	4.31.1	\N	\N	0537993386
1760536349141-5	PhamDuyHuy	db/changelog/15-01-changelog.sql	2025-10-15 14:19:54.772041	10	EXECUTED	9:0a704bd50dfd2bd98768409b5c2cbb96	sql		\N	4.31.1	\N	\N	0537993386
\.


--
-- TOC entry 3415 (class 0 OID 66810)
-- Dependencies: 218
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3425 (class 0 OID 0)
-- Dependencies: 219
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 34, true);


--
-- TOC entry 3419 (class 0 OID 0)
-- Dependencies: 3418 3420
-- Data for Name: 58409..58410; Type: BLOBS; Schema: -; Owner: postgres
--

BEGIN;

SELECT pg_catalog.lo_open('58409', 131072);
SELECT pg_catalog.lowrite(0, '\x58696e206368c3a06f');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('58410', 131072);
SELECT pg_catalog.lowrite(0, '\x4368c3a06f2062e1baa16e2c2074c3b4692063c3b3207468e1bb83206769c3ba702067c3ac2063686f2062e1baa16e2068c3b46d206e61793f');
SELECT pg_catalog.lo_close(0);

COMMIT;

--
-- TOC entry 3265 (class 2606 OID 66830)
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- TOC entry 3263 (class 2606 OID 66814)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 1259 OID 75440)
-- Name: idx_conversation_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversation_id ON public.chat_message USING btree (conversation_id);


--
-- TOC entry 3267 (class 1259 OID 75441)
-- Name: idx_conversation_id_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversation_id_timestamp ON public.chat_message USING btree (conversation_id, ts);


--
-- TOC entry 3268 (class 2606 OID 75442)
-- Name: chat_message fk_chat_message_on_parent_message; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fk_chat_message_on_parent_message FOREIGN KEY (parent_message_id) REFERENCES public.chat_message(id);


-- Completed on 2025-11-04 11:26:16

--
-- PostgreSQL database dump complete
--

