--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.5

-- Started on 2025-11-04 11:30:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 57656)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 57661)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 57667)
-- Name: media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp without time zone NOT NULL,
    updated_by character varying(255),
    is_deleted boolean NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by character varying(255),
    public_id character varying(255) NOT NULL,
    url character varying(500) NOT NULL,
    secure_url character varying(500) NOT NULL,
    media_type character varying(20) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.media OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 57666)
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3414 (class 0 OID 57656)
-- Dependencies: 217
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1757207654533-1	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.631834	1	EXECUTED	9:6a919587b3c1ac35c2e3900f2bd37d77	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-2	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.716735	2	EXECUTED	9:5aa030fe9dbe3da6d4b830afbd67ef1b	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-3	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.751137	3	EXECUTED	9:804160c46dd2fad47b4fed1b58c88446	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-4	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.799476	4	EXECUTED	9:2c84e07aa232d1f452de5dccb15ab9d2	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-5	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.867744	5	EXECUTED	9:7277766fe687f281888c5bba7d937ef3	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-6	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.900609	6	EXECUTED	9:785639a21c93300645a5d7505236bb92	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-7	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.924137	7	EXECUTED	9:d26a771cff3cf40690b7ceac99bc7ed8	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-8	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.954311	8	EXECUTED	9:459c8aca8f86ffb409b8932a7200ae4d	sql		\N	4.31.1	\N	\N	7320665796
1757360479719-7	PhamDuyHuy	db/changelog/ddl/002-changelog.sql	2025-09-08 23:40:36.937382	9	EXECUTED	9:96e885b19d8df269c9224d1306808c83	sql		\N	4.31.1	\N	\N	7374830585
1757360479719-1	PhamDuyHuy	db/changelog/ddl/002-changelog.sql	2025-09-08 23:40:37.080549	10	EXECUTED	9:284d63fe476a6816910200df6de13cfc	sql		\N	4.31.1	\N	\N	7374830585
1757426207281-2	PhamDuyHuy	db/changelog/ddl/003-changelog.sql	2025-09-09 22:01:53.20994	11	EXECUTED	9:c0014eb8e44d6b583b6467a9494cb56b	sql		\N	4.31.1	\N	\N	7455309700
\.


--
-- TOC entry 3415 (class 0 OID 57661)
-- Dependencies: 218
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3417 (class 0 OID 57667)
-- Dependencies: 220
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media (id, created_at, created_by, updated_at, updated_by, is_deleted, deleted_at, deleted_by, public_id, url, secure_url, media_type, is_active) FROM stdin;
1	2025-09-09 13:51:29.941817	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-09 13:51:29.942249	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_lu4dyf	http://res.cloudinary.com/de0ler3wa/image/upload/v1757425888/hotels/file_lu4dyf.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757425888/hotels/file_lu4dyf.png	image	t
2	2025-09-10 00:23:34.284981	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 00:23:34.285078	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_uubyof	http://res.cloudinary.com/de0ler3wa/image/upload/v1757463812/hotels/file_uubyof.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757463812/hotels/file_uubyof.png	image	t
3	2025-09-10 01:55:47.281108	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 01:55:47.281168	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	room-types/file_yr53mb	http://res.cloudinary.com/de0ler3wa/image/upload/v1757469346/room-types/file_yr53mb.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757469346/room-types/file_yr53mb.png	image	t
4	2025-09-10 05:01:08.164483	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 05:01:08.16455	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	rooms/file_whbzic	http://res.cloudinary.com/de0ler3wa/image/upload/v1757480466/rooms/file_whbzic.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757480466/rooms/file_whbzic.png	image	t
5	2025-09-10 10:38:40.935115	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 10:38:40.935201	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_fpavup	http://res.cloudinary.com/de0ler3wa/image/upload/v1757500718/hotels/file_fpavup.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757500718/hotels/file_fpavup.png	image	t
6	2025-09-11 23:35:53.912352	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-11 23:35:53.912421	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_tb6d53	http://res.cloudinary.com/de0ler3wa/image/upload/v1757633752/hotels/file_tb6d53.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757633752/hotels/file_tb6d53.png	image	t
7	2025-09-19 10:54:58.787149	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-19 10:54:58.787229	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_jpiuhu	http://res.cloudinary.com/de0ler3wa/image/upload/v1758279296/hotels/file_jpiuhu.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1758279296/hotels/file_jpiuhu.jpg	image	t
8	2025-09-19 10:55:14.104634	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-19 10:55:14.104657	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_vlgtbq	http://res.cloudinary.com/de0ler3wa/image/upload/v1758279313/hotels/file_vlgtbq.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1758279313/hotels/file_vlgtbq.jpg	image	t
9	2025-09-19 10:55:22.955935	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-19 10:55:22.956008	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_lmrb2p	http://res.cloudinary.com/de0ler3wa/image/upload/v1758279320/hotels/file_lmrb2p.webp	https://res.cloudinary.com/de0ler3wa/image/upload/v1758279320/hotels/file_lmrb2p.webp	image	t
10	2025-09-19 10:55:34.551416	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-19 10:55:34.551449	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_p08o10	http://res.cloudinary.com/de0ler3wa/image/upload/v1758279331/hotels/file_p08o10.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1758279331/hotels/file_p08o10.jpg	image	t
11	2025-10-09 17:19:04.842957	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-09 17:19:04.843122	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	avatars/file_ngkcm6	http://res.cloudinary.com/de0ler3wa/image/upload/v1760030342/avatars/file_ngkcm6.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1760030342/avatars/file_ngkcm6.png	image	t
12	2025-10-09 18:24:03.288704	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-09 18:24:03.289255	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_mhb7jf	http://res.cloudinary.com/de0ler3wa/image/upload/v1760034240/hotels/file_mhb7jf.webp	https://res.cloudinary.com/de0ler3wa/image/upload/v1760034240/hotels/file_mhb7jf.webp	image	t
13	2025-10-09 18:27:23.862296	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-09 18:27:23.862315	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_e7rhq0	http://res.cloudinary.com/de0ler3wa/image/upload/v1760034442/hotels/file_e7rhq0.webp	https://res.cloudinary.com/de0ler3wa/image/upload/v1760034442/hotels/file_e7rhq0.webp	image	t
14	2025-10-09 18:28:53.433015	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-09 18:28:53.433124	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_bcnmud	http://res.cloudinary.com/de0ler3wa/image/upload/v1760034531/hotels/file_bcnmud.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760034531/hotels/file_bcnmud.jpg	image	t
15	2025-10-12 10:16:56.20583	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 10:16:56.20596	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airports/AC9h4nq6AJu1zUSy7Nj-YkMjyGytQ0cuUKHBNIKdALlljqykfd9Ynrck4S0QqAfOmV5gow16qrJtJL7OdBddKnvrbNAZjk99dsyqlN_S4SDCIdG0HJl8njHUkK2ZkwOK5bqzR1FBoh9k_w408-h306-k-no_pydlfs	http://res.cloudinary.com/de0ler3wa/image/upload/v1760264214/airports/AC9h4nq6AJu1zUSy7Nj-YkMjyGytQ0cuUKHBNIKdALlljqykfd9Ynrck4S0QqAfOmV5gow16qrJtJL7OdBddKnvrbNAZjk99dsyqlN_S4SDCIdG0HJl8njHUkK2ZkwOK5bqzR1FBoh9k_w408-h306-k-no_pydlfs.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760264214/airports/AC9h4nq6AJu1zUSy7Nj-YkMjyGytQ0cuUKHBNIKdALlljqykfd9Ynrck4S0QqAfOmV5gow16qrJtJL7OdBddKnvrbNAZjk99dsyqlN_S4SDCIdG0HJl8njHUkK2ZkwOK5bqzR1FBoh9k_w408-h306-k-no_pydlfs.jpg	image	t
16	2025-10-12 10:17:35.558035	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 10:17:35.558055	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airports/AC9h4nrZEGmjO9Ms8-VAUn9-MshD66o2cb2wYDeqocLN6PvIBdBU8G3SavlwD_aSf4F48mGIh7lBkGcKL5x_gdhs6DB5AJXItygJZMlIyWBNZB1u_m3-pdYV30HI7pbcdhPPpeiP373CaiDzcG5e_w408-h306-k-no_j3gysw	http://res.cloudinary.com/de0ler3wa/image/upload/v1760264253/airports/AC9h4nrZEGmjO9Ms8-VAUn9-MshD66o2cb2wYDeqocLN6PvIBdBU8G3SavlwD_aSf4F48mGIh7lBkGcKL5x_gdhs6DB5AJXItygJZMlIyWBNZB1u_m3-pdYV30HI7pbcdhPPpeiP373CaiDzcG5e_w408-h306-k-no_j3gysw.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760264253/airports/AC9h4nrZEGmjO9Ms8-VAUn9-MshD66o2cb2wYDeqocLN6PvIBdBU8G3SavlwD_aSf4F48mGIh7lBkGcKL5x_gdhs6DB5AJXItygJZMlIyWBNZB1u_m3-pdYV30HI7pbcdhPPpeiP373CaiDzcG5e_w408-h306-k-no_j3gysw.jpg	image	t
17	2025-10-12 14:21:38.366245	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 14:21:38.366422	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airlines/vietnam-airline-logo_qcvusc	http://res.cloudinary.com/de0ler3wa/image/upload/v1760278895/airlines/vietnam-airline-logo_qcvusc.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760278895/airlines/vietnam-airline-logo_qcvusc.jpg	image	t
18	2025-10-12 14:53:40.089958	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 14:53:40.090029	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airlines/logo-bamboo-airways-inkythuatso-13-16-29-54_fskxvm	http://res.cloudinary.com/de0ler3wa/image/upload/v1760280816/airlines/logo-bamboo-airways-inkythuatso-13-16-29-54_fskxvm.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760280816/airlines/logo-bamboo-airways-inkythuatso-13-16-29-54_fskxvm.jpg	image	t
19	2025-10-12 14:55:07.219796	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 14:55:07.219817	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airlines/images_crzafs	http://res.cloudinary.com/de0ler3wa/image/upload/v1760280903/airlines/images_crzafs.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1760280903/airlines/images_crzafs.png	image	t
20	2025-10-12 14:55:49.795985	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 14:55:49.796008	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airlines/images_esgkas	http://res.cloudinary.com/de0ler3wa/image/upload/v1760280948/airlines/images_esgkas.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1760280948/airlines/images_esgkas.png	image	t
21	2025-10-12 16:32:59.484708	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 16:32:59.484926	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	airports/AC9h4nrl06ZoMhp3I8IxEkBiJAaWYGVxk0LV1NExlwt1Y3Nz3-3TspGCzA_a4ySsLEOf2YF7k3mcpFHbpw8d9IIJZTN_Z4Nojc8Kb7FvqPauZneuJtTPBi_qZeGGWmY8zEqyA--5U-kWbQ_w408-h306-k-no_a6hxym	http://res.cloudinary.com/de0ler3wa/image/upload/v1760286776/airports/AC9h4nrl06ZoMhp3I8IxEkBiJAaWYGVxk0LV1NExlwt1Y3Nz3-3TspGCzA_a4ySsLEOf2YF7k3mcpFHbpw8d9IIJZTN_Z4Nojc8Kb7FvqPauZneuJtTPBi_qZeGGWmY8zEqyA--5U-kWbQ_w408-h306-k-no_a6hxym.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760286776/airports/AC9h4nrl06ZoMhp3I8IxEkBiJAaWYGVxk0LV1NExlwt1Y3Nz3-3TspGCzA_a4ySsLEOf2YF7k3mcpFHbpw8d9IIJZTN_Z4Nojc8Kb7FvqPauZneuJtTPBi_qZeGGWmY8zEqyA--5U-kWbQ_w408-h306-k-no_a6hxym.jpg	image	t
22	2025-10-12 17:07:47.455699	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 17:07:47.455842	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_tu0udm	http://res.cloudinary.com/de0ler3wa/image/upload/v1760288865/hotels/file_tu0udm.webp	https://res.cloudinary.com/de0ler3wa/image/upload/v1760288865/hotels/file_tu0udm.webp	image	t
23	2025-10-12 17:08:49.858531	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 17:08:49.858561	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/86895305_ccfyhb	http://res.cloudinary.com/de0ler3wa/image/upload/v1760288927/hotels/86895305_ccfyhb.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760288927/hotels/86895305_ccfyhb.jpg	image	t
24	2025-10-12 17:11:07.615641	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 17:11:07.61567	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/AF1QipMA3dmc6SrKjg4gaj2rErnBn8xtc4pYDK549R17_s1360-w1360-h1020-rw_vwoes3	http://res.cloudinary.com/de0ler3wa/image/upload/v1760289066/hotels/AF1QipMA3dmc6SrKjg4gaj2rErnBn8xtc4pYDK549R17_s1360-w1360-h1020-rw_vwoes3.webp	https://res.cloudinary.com/de0ler3wa/image/upload/v1760289066/hotels/AF1QipMA3dmc6SrKjg4gaj2rErnBn8xtc4pYDK549R17_s1360-w1360-h1020-rw_vwoes3.webp	image	t
25	2025-10-12 17:19:08.420421	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 17:19:08.420444	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/700367660_d47ysb	http://res.cloudinary.com/de0ler3wa/image/upload/v1760289545/hotels/700367660_d47ysb.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760289545/hotels/700367660_d47ysb.jpg	image	t
26	2025-10-12 17:21:27.499702	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-12 17:21:27.49972	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/fu2_ppcv1i	http://res.cloudinary.com/de0ler3wa/image/upload/v1760289684/hotels/fu2_ppcv1i.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1760289684/hotels/fu2_ppcv1i.jpg	image	t
27	2025-10-23 02:40:04.853568	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-10-23 02:40:04.853661	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/665426576_wuqpeg	http://res.cloudinary.com/de0ler3wa/image/upload/v1761187203/hotels/665426576_wuqpeg.jpg	https://res.cloudinary.com/de0ler3wa/image/upload/v1761187203/hotels/665426576_wuqpeg.jpg	image	t
\.


--
-- TOC entry 3423 (class 0 OID 0)
-- Dependencies: 219
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_id_seq', 27, true);


--
-- TOC entry 3262 (class 2606 OID 57665)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 57673)
-- Name: media pk_media; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT pk_media PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 57675)
-- Name: media uc_media_public; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT uc_media_public UNIQUE (public_id);


--
-- TOC entry 3263 (class 1259 OID 57676)
-- Name: idx_media_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_media_active ON public.media USING btree (is_active);


--
-- TOC entry 3264 (class 1259 OID 57680)
-- Name: idx_media_public_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_media_public_id ON public.media USING btree (public_id);


-- Completed on 2025-11-04 11:30:42

--
-- PostgreSQL database dump complete
--

